### ISSUE TITLE
[FEATURE] Publish solutions

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [laget-se/publish-nuget#2]
**Is your feature request related to a problem? Please describe.**
Let's say we have 100 projects, how are we going to run the actions one by one for each file?

**Describe the solution you'd like**
Allow build by solution, and filter all the nupkg artifacts as uploadables

**Describe alternatives you've considered**
Copy and pasting 100 similar entries using YAML anchors (https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/)

**Additional context**
This is very common if you have code autogeneration (especially when it comes to OpenAPI and Linq2db)

**Comment by gonace** [comment]
Hi @wizpresso-steve-cy-fan
We forked the repository `publish-nuget` to extend the functionality made by the original author only to fit our needs, and since we do not need this functionality we'll not implement this on our own.

You're welcome to create a pull request with the requested functionality or fork it an change it to fit your needs.
